Leaderboard: final touches
Mihndim2020/LeaderBoard-List-App pull request #3
Opened 2021-07-29 18:15 UTC by Mihndim2020

For this pull request, I have styled the App using CSS3.

2021-07-29 18:44 UTC, bellom requested changes
## Hi @Mihndim2020  👏 , 

### Awesome job so far!! :+1: 

#### You have done wonderfully well setting up linter and good commit messages 🔥, However, you passed `almost` all the checklist for this project :+1: just a few issues left to work on............ :slightly_smiling_face: 

# Status: Required Changes! ♻️ 

**1. Let's stick to the wireframe design provider for this project.**

![image](https://user-images.githubusercontent.com/31897434/127547166-8cd408dd-09e6-4e97-b8b5-1b975c02c6a1.png)

Your design:
![image](https://user-images.githubusercontent.com/31897434/127547964-c97c84d4-b030-454f-b261-234fdd56bdac.png)

**Hint:** 
_- Kindly move the h2 tag with `Recent scores` and the `refresh` button to the top of the card._
_- Fix the `submit button, it is overlapping._

**2. Kindly check the comments under the review.**

### ♻️ Kindly re-submit for review after making all those changes :slightly_smiling_face: Thumps -up await you.....

### Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-07-29 18:44 UTC, bellom commented on README.md
If you check the [Microverse template](https://github.com/microverseinc/readme-template) you will see there is a section where you're supposed to add `Live Demo Link`.

Kindly add Live Demo Link.

2021-07-29 21:45 UTC, Mihndim2020 commented on README.md
Demo link added

2021-07-29 21:46 UTC, Mihndim2020 commented
All **requested changes** implemented. Thank you for your feedback.

2021-07-29 22:09 UTC, MahmoudBakr23 requested changes
Hi @Mihndim2020 😃, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

> Keep in mind that your long hours of work are appreciated. However, the code review process is for improving the code you wrote, and not for criticizing it. 😄

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

N/A

Cheers and Happy coding!👏👨‍💻💻

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-07-29 22:09 UTC, MahmoudBakr23 commented on src/style.css
>    text-align: left;
- [ ] Kindly fix the styling spacing issues with the app. See the image below for more information 😊🙏🏻
![Screenshot_2021-07-30-00-01-33-31](https://user-images.githubusercontent.com/47625407/127572024-cea49fce-563c-41b5-af14-30d605498366.jpg)

2021-07-29 23:55 UTC, Mihndim2020 commented
Spacing issue fixed. Thanks for your feedback.

2021-07-30 00:24 UTC, hemant-soni-vst-au4 approved these changes
Hi, @Mihndim2020, 

Good work on making the requested changes. 🚀 
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 

## Congratulations! 🎉 

![Alt Text](https://media.giphy.com/media/jkZhf5HyZkLbBzzZsn/giphy.gif)

Cheers and happy coding 😃

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. You can mention me (@hemant-soni-vst-au4) so I can see your comments and respond.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-07-30 14:12 UTC, merged